# -*- coding: utf-8 -*-
"""Laboratório passo a passo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JB2lVqFiltYRBs0FzTK0RJzZQ_xNW1bw
"""

import mongomock
from pymongo.errors import PyMongoError

print("INICIANDO O LABORATÓRIO PRÁTICO DE BACK-END")

cliente = mongomock.MongoClient()
db = cliente['loja_banco']
produtos = db['produtos']

print ("[CONEXÃO]: Simulador do MongoDB iniciado com sucesso!")

novo_item = {
    "nome": "Teclado Mecânico Gamer",
    "preco": 189.90,
    "estoque": 25
}

retorno = produtos.insert_one(novo_item)

print(f"[CREATE]: Item salvo! O banco carimbou o ID único: {retorno.inserted_id}")

print("\n--- [RED]: CONSULTANDO OS ITENS DA GAVETA ---")

todos_produtos = produtos.find()

for p in todos_produtos:
  print(f"Produto: {p['nome']} | Preço: R$ {p['preco']} | Estoque: {p['estoque']}")


filtro_busca ={"nome": "Teclado Mecânico Gamer"}
nova_informação = {"$set": {"preco": 219.90}}

produtos.update_one(filtro_busca, nova_informação)
print("\n [UPDATE]: O preço do teclado foi reajustadado no banco!")

produto_conferido = produtos.find_one(filtro_busca)
print(f" [CONFERÊNCIA]: Novo preço verificado no banco: R$ {produto_conferido['preco']}")
produtos.create_index([("preco", 1)])
print("\n [OTIMIZAÇÃO]: Índice de preços criado! Consultas agora são instantâneas.")

print("\n [TRANSAÇÃO]: Iniciando uma simulação de venda segura...")

produtos.insert_one({"nome": "Mouse Sem Fio", "preco": 50.0, "estoque": 5})

# The following block is commented out because mongomock does not support sessions/transactions.
# To use transactions, a real MongoDB server is required.
# with cliente.start_session() as sessao:
#     with sessao.start_transaction():
#
#         produtos.update_one({"nome": "Mouse Sem Fio"}, {"$inc": {"estoque": -1}}, session=sessao)
#
#         db['vendas'].insert_one({"item": "Mouse Sem Fio", "qtd": 1, "status": "Pago"}, session=sessao)
#
#         print("[TRANSAÇÃO]: Sucesso! Estoque reduzido e recibo gerado juntos.")

print(" [AVISO]: O BLOCO DE TRANSAÇÃO foi pulado, pois mongomock não suporta sessões.\nPara usar transações, é necessário um servidor MongoDB real.")

print("\n=======================================================")